### ISSUE TITLE
"let-" is only supported on ng-template elements in Angular 5.0.0

### ISSUE THREAD

**Issue by MvS-IT** [valor-software/ngx-bootstrap#3024]
### Bug description or feature request:
After upgrade to angular 5.0.0 the following error is emcountered:
Uncaught Error: Template parse errors:
"let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec"): ng:///DatepickerModule/DayPickerComponent.html@52:37
"let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec"): ng:///DatepickerModule/DayPickerComponent.html@52:58
    at syntaxError (compiler.js:466)
    at TemplateParser.parse (compiler.js:24314)
    at JitCompiler._parseTemplate (compiler.js:33701)
    at JitCompiler._compileTemplate (compiler.js:33676)
    at eval (compiler.js:33578)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:33578)
    at eval (compiler.js:33448)
    at Object.then (compiler.js:455)
    at JitCompiler._compileModuleAndComponents (compiler.js:33447)
syntaxError @ compiler.js:466
TemplateParser.parse @ compiler.js:24314
JitCompiler._parseTemplate @ compiler.js:33701
JitCompiler._compileTemplate @ compiler.js:33676
(anonymous) @ compiler.js:33578
JitCompiler._compileComponents @ compiler.js:33578
(anonymous) @ compiler.js:33448
then @ compiler.js:455
JitCompiler._compileModuleAndComponents @ compiler.js:33447
JitCompiler.compileModuleAsync @ compiler.js:33363
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:230
PlatformRef.bootstrapModule @ core.js:5446
(anonymous) @ main.ts:12
../../../../../src/main.ts @ main.bundle.js:275
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:298
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 5.0.0

Bootstrap: 3.3.7

### Build system: 
Angular CLI 1.5.0, + webpack@3.8.1

**Comment by IlyaSurmay** [comment]
Use ngx-bootstrap@2.0.0-beta.8

**Comment by MvS-IT** [comment]
Thanks!

**Comment by MvS-IT** [comment]
Sorry, but when serving my app with --aot option like in ng serve --aot, i now see all kinds of warnings concerning private properties that should be public:
Property 'xxx' is private and only accessible within class 'yyyyComponent'.
Using ng serve only is working, but that is not acceptable in our production env.

**Comment by IlyaSurmay** [comment]
Which components are throwing errors?

**Comment by MvS-IT** [comment]
DatepickerModule, RatingModule and TypeaheadModule

**Comment by valorkin** [comment]
Show any error complete error stack, I am sure it's private properties in your components, not ngx-bs

**Comment by saurabhThawari** [comment]
I am still getting error for 
"let-" is only supported on ng-template elements.
</thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec"): ng:///DatepickerModule/DayPickerComponent.html@38:37

Even though i have updated my ngx-bootstrap with ngx-bootstrap@2.0.0-beta.8

**Comment by IlyaSurmay** [comment]
@saurabhThawari sample repo or plunkr/stackblitz with reproduction please 
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by saurabhThawari** [comment]
thanks for the reply, issue has been resolved, I was using both ng2-bootstrap and ngx-bootstrap ,I used  Ng2BootstrapModule from ng2-bootstrap in app.module , and I had removed that Module from app.module with ng2-bootstrap dependencies in package.json and issue got resolved

**Comment by leifwalder** [comment]
@saurabhThawari please could you elaborate more what the 'fix' was for you? I am stuck in the same problem.

**Comment by leifwalder** [comment]
I still couldnt get this to work, even though I followed up on advice from this issue like Use ngx-bootstrap@2.0.0-beta.8.

...any help is appreciated
https://stackoverflow.com/questions/47866158/let-is-only-supported-on-ng-template-elements

**Comment by Valery-vs** [comment]
+1

**Comment by thatchej** [comment]
I am currently updated all the way to `ngx-bootstrap@2.0.0-rc.0` and I'm still getting exactly the same error. Did this regression get re-added after `2.0.0-beta.8`?

**Comment by saurabhThawari** [comment]
@leifwalder , I have added both the  ng2-bootstrap  and ngx-bootstrap in "**dependencies**" under pakage.json file, thats why I was stuck with the issue, removing of  ng2-bootstrap from the dependencies helped to resolve my issue

**Comment by BBaysinger** [comment]
I am having this issue. But I am not using both ng2-bootstrap and ngx-bootstrap.

**Comment by valorkin** [comment]
You should use ngx-bootstrap v2+
