### ISSUE TITLE
Top Right Navbar dropdown goes off the right side of the screen

### ISSUE THREAD

**Issue by dessalines** [valor-software/ngx-bootstrap#625]
Example of top right navbar dropdown : 
![chatpracticeui 2016-06-18 15-51-08](https://cloud.githubusercontent.com/assets/930215/16174177/84cc11a0-356c-11e6-8b12-7e438f87e0d2.png)

It creates a scrollbar, which goes to the right side, and is unnecessary, the dropdown should just auto-place left, or provide an alignment option.

**Comment by valorkin** [comment]
auto place, yes
working on updating positioning service

**Comment by valorkin** [comment]
Duplicate, working on new positioning service

**Comment by hacenator** [comment]
![out](https://cloud.githubusercontent.com/assets/290562/24612679/9fa07de4-188e-11e7-9c3d-e3781853f6aa.PNG)
the same behaviour in 1.6.1

**Comment by valorkin** [comment]
not the same, because now you can configure a position of attachment

**Comment by hacenator** [comment]
Do you mean 'placement' or class 'dropdown-menu-left/right'?
So if I want to put it at the right side, it always be out of screen because there is no 'auto' placement for attachments anymore?

**Comment by valorkin** [comment]
Check docs please, there are a sample for it

**Comment by hacenator** [comment]
Unfortunately there is nothing in docs that can answer my question - why it worked before, and broken in 1.6.1.

**Comment by valorkin** [comment]
This is your case http://valor-software.com/ng2-bootstrap/#/dropdowns#alignment

**Comment by hacenator** [comment]
Yes, thank you, Dmitry. I already fixed it. I just meant it worked before and doesn't works only in 1.6.1 (perhaphs starting from 1.5.0), so it's should be marked as "BREAKING CHANGES" in changeslog or smth similar, because dropdown doesn't work as before. there is a lot of info in 1.5.0 about dropdown, but nothing about 'alignment'.

**Comment by valorkin** [comment]
Oh, this. Any idea how to describe it?

**Comment by hacenator** [comment]
I think for me the problem was in .pull-right which is deprecated in bootstrap 3.1.0. But I don't know how it's worked before (I mean internally in bootstrap), and why .pull-right doesn't works as before. So when I added '.dropdown-menu-left' (yes, left), it was fixed, because with that alignment it not so close to the right screen border anymore. Actually, I didn't tested it with long text in menu, so maybe it still can out of the screen in this case.

Maybe that text can be used (from bootstrap docs). Because there is notification that 'pull-right' is deprecated:
> Deprecated .pull-right alignment
> As of v3.1.0, we've deprecated .pull-right on dropdown menus. To right-align a menu, use .dropdown-menu-right. Right-aligned nav components in the navbar use a mixin version of this class to automatically align the menu. To override it, use .dropdown-menu-left.

**Comment by rochapablo** [comment]
I was having the same problem, but with bootstrap v4-alpha. I tried use [placement	
](http://valor-software.com/ngx-bootstrap/#/dropdowns#api-reference) but it didn't work.

To fix here's what I did:

```
.dropdown-menu { right: 0; left: auto; }
```

**Comment by IerominSergii** [comment]
@rochapablo Thank you! It works with it!)

`.dropdown-menu { right: 0; left: auto; }`

**Comment by columbian-chris** [comment]
For a more recent solution than this (for people from the future still looking here), add the `dropdown-menu-right` class to your `dropdown-menu`.

**Comment by mecfletcher** [comment]
@columbian-chris This still isn't working, any idea why?

<div class="dropdown-menu dropdown-menu-right">

**Comment by phuongpentest** [comment]
when you in sm mode it go off of the left side. How?
