### ISSUE TITLE
RC5 Modal not working in multiple components

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#854]
Hi,

I am using Angular RC5 and am able to open modal box in the root component (app-component) using `viewProviders: [BS_VIEW_PROVIDERS]` and keeping the modal box and button in the component template.

However when i do the same for other components, it triggers an error:

```
Error: Uncaught (in promise): No provider for AppComponent!
```

Any ideas how to fix this please?

**Comment by jimmythesaint82** [comment]
I'm also getting this error

**Comment by rspenc29** [comment]
Adding `BS_VIEW_PROVIDERS` to `providers` instead of `viewProviders` seems to fix this but I haven't really dug into the code to see why.

**Comment by hassanasad** [comment]
@rspenc29 wow, let me try it with your technique :)

**Comment by hassanasad** [comment]
@rspenc29 I tried, its not working for me. Everything works fine if the modal box is in the root component (appComponent). I get error when i put it in some other component. 

This is the error that i get:

```
EXCEPTION: Error: Uncaught (in promise): No provider for AppComponent!
```

P.S: Are you using RC5 and webpack?

**Comment by rspenc29** [comment]
This works for me. I'm also using the `feat-rc5` branch

```
@NgModule({
    imports: [
        // ...
        ModalModule,
    ],
    declarations: [
        // ...
    ],
    providers: [ BS_VIEW_PROVIDERS ],
})

export class AppModule {}
```

I did however have an issue with the backdrop and for now i'm using `[config]="{backdrop: false}"` until i have time to troubleshoot it or until an update is released.

**Comment by hassanasad** [comment]
Thanks @rspenc29 - I will give it a shot with `feat-rc5` branch in a little while.

**Comment by jimmythesaint82** [comment]
Yeah that fix doesn't work for me still get 
EXCEPTION: Error: Uncaught (in promise): No provider for App

on feat-rc5

**Comment by noxborough** [comment]
I'm experiencing the same issue with RC5. Only i'm trying to access Modals from a lazy loaded component inside of an NgModule.  The offending code in ng2-bootstrap is inside the **components-helper.service.js** (see below)

```
ComponentsHelper.prototype.getRootViewContainerRef = function () {
    // The only way for now (by @mhevery)
    // https://github.com/angular/angular/issues/6446#issuecomment-173459525
    // this is a class of application bootstrap component (like my-app)
    var classOfRootComponent = this.applicationRef.componentTypes[0];
    // this is an instance of application bootstrap component
    var appInstance = this.injector.get(classOfRootComponent);
    return appInstance.viewContainerRef;
};
```

The **classOfRootComponent** has a reference to my root component type (for most people this is AppComponent).  The **injector** is not the root injector, but rather the injector associated with my lazy loaded module. So I'm guessing it does not have access to the root component instance of AppComponent.  And so it bombs out. 

I have not been able to figure out a work around.

**Comment by a5hik** [comment]
same issue here.

**Comment by a5hik** [comment]
Is it working with feat-rc5? how do you got that via `npm install`

**Comment by kamikaze** [comment]
+1

**Comment by noxborough** [comment]
I was able to get it to work using the feat-rc5 branch after some refactoring to import the ng2-bootstrap **ModalModule**. But it only worked after i set **this.myModal.config.backdrop = false** (instead of **"static"**).

Which seems to be the same solution that @rspenc29 found.  I think if you use the "static" value, it tries to find the root component in the injector and can't resolve it.

@a5hik - i don't think you can install it via npm. i just downloaded it, and extracted it into my project until they do a full RC5 compatible release.

**Comment by rspenc29** [comment]
To use `feat-rc5`, just do the following...

```
cd node_modules
git clone https://github.com/valor-software/ng2-bootstrap.git
cd ng2-bootstrap
git checkout feat-rc5
npm install
```

**Comment by a5hik** [comment]
Hi now I'm able to use feat-rc5, I'm importing the ng2-bootstrap module like below.

`import {DatepickerModule} from 'ng2-bootstrap/components/datepicker/datepicker.module';
import {DropdownModule} from 'ng2-bootstrap/components/dropdown/dropdown.module';
import {ModalModule} from 'ng2-bootstrap/components/modal/modal.module';`

However I get the same error when I try to use the modal ..in my lazy loaded module.

I do specify the `providers: [BS_VIEW_PROVIDERS]` in my module and removed the 'viewProviders` from the component code as suggested.

But I still face the same error.

`No provider for AppComponent!`

I just wonder what I'm missing here, or how it works for others.

**Comment by rspenc29** [comment]
The error is caused by the backdrop. Just disable it until they fix it.

**Comment by a5hik** [comment]
I started working after I change `[config]="{backdrop: 'static'}" to [config]="{backdrop: false}"

**Comment by a5hik** [comment]
thanks @rspenc29 @noxborough

**Comment by a5hik** [comment]
I face other issue, that If I run in `--prod` mode.. I get the below errors..

`Can't bind to 'activeDate' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'activeDate' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
    <datepicker-inner [ERROR ->][activeDate]="activeDate"
                      (update)="onUpdate($event)"
                      [da"): a@1:22
Can't bind to 'datepickerMode' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'datepickerMode' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("r [activeDate]="activeDate"
                      (update)="onUpdate($event)"
                      [ERROR ->][datepickerMode]="datepickerMode"
                      [initDate]="initDate"
                      ["): a@3:22
Can't bind to 'initDate' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'initDate' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("e)="onUpdate($event)"
                      [datepickerMode]="datepickerMode"
                      [ERROR ->][initDate]="initDate"
                      [minDate]="minDate"
                      [maxDate]="maxD"): a@4:22
Can't bind to 'minDate' since it isn't a known property of 'datepicker-inner'.`

**Comment by batchu** [comment]
@a5hik  See here https://github.com/angular/angular/issues/10618

Also, can you post a quick guide on how to use feat-rc5? I updated my package.json to
    "ng2-bootstrap": "https://github.com/valor-software/ng2-bootstrap.git#feat-rc5",

But now I only see .md files downloaded. I do not see any .ts files.
So I checked out the project in git as rspenc29 suggested. my npm build fails. How do I get this to work?

**Comment by jimmythesaint82** [comment]
You need to pull from git, detailed above from rob.

**Comment by a5hik** [comment]
I tried with the webpack upgrade to get the `prod` version working..But ended up in having the below issue. I used the angular cli from the master repo. 

https://github.com/angular/angular-cli/issues/1636

**Comment by hassanasad** [comment]
I am using v1.1.1 with RC6 and i am still getting the same error:
"No provider for AppComponent!"

Perhaps i am missing anything?

I do have to `hack` in the main AppComponent:

```
import { ViewContainerRef } from '@angular/core';
...
constructor(
        private renderer: Renderer, 
        public viewContainerRef:ViewContainerRef,
        ) {
        this.viewContainerRef = viewContainerRef;
    }
```

**Comment by valorkin** [comment]
ng2-bootstrap doesn't use or requires any AppComponent
Please do full text search in your app

**Comment by hassanasad** [comment]
doing this in for the modal fixes the issue `[config]="{backdrop: false}"` - Perhaps its looking for a backdrop in the main AppComponent?

**Comment by hassanasad** [comment]
AppComponent is my main component (which has the hack as mentioned in the comment above)

**Comment by JonathanJJudge** [comment]
Just want to chime in about this problem. Would love to see a fix released. Thanks!

**Comment by dhardtke** [comment]
Have the same issue with a modal inside lazy-loaded components (using the new router).

**Comment by valorkin** [comment]
Seems as a quick fix I will have to disable attach to body, any one have repo so I can reproduce?
Because it is working fine for me >.<

**Comment by flibbertigibbet** [comment]
To reproduce on [this repo using RC5](https://github.com/azavea/climate-change-lab/):
- `cp example/constants.ts.example src/app/constants.ts` (queries will fail due to missing API key, but that's fine for testing modal)
- `npm install` and `npm start`, then view [this page](http://localhost:3100/#/lab)
- Click 'Select Models' button in top nav bar. Modal opens fine with no background
- Remove config option [here](https://github.com/azavea/climate-change-lab/blob/develop/src/app/lab/lab.component.html#L74) and click 'Select Models'; modal fails to open with console error `Unhandled Promise rejection: Cannot read property 'parentInjector' of undefined`

**Comment by dhardtke** [comment]
But that's a different error message than we guys get (which is `No provider for AppComponent`)

**Comment by flibbertigibbet** [comment]
Using `BS_VIEW_PROVIDERS` as noted by @rspenc29 fixed immediate `No provider for AppComponent` error, then resulting in error above, which required the additional background workaround.

**Comment by dhardtke** [comment]
I don't have a `BS_VIEW_PROVIDERS` constant with the latest version, so I guess it is exclusive to the rc5 branch.

**Comment by hassanasad** [comment]
Yeah its not available in the latest version. For now `[config]="{backdrop: false}"` is the only way i found to get it working.

**Comment by amirjelo** [comment]
@hassanasad your solution just worked for the first time that modal opened , next time you open the modal , this error cames up : `Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter`

**Comment by noxborough** [comment]
@valorkin 
I tested with RC6 and ng2-bootstrap v1.1.2. 

I can confirm that **config.backdrop = "static** works fine with eagerly loaded components.

But if the component that creates the modal dialog is part of a module that is lazy loaded (and it sets config.backdrop = "static"), than I still get the same error: "No provider for AppComponent!"

As i stated in an earlier post, the error manifests itself in **components-helper.service.js** when trying to get the root app component from the injector.

```
ComponentsHelper.prototype.getRootViewContainerRef = function () {
    // The only way for now (by @mhevery)
    // https://github.com/angular/angular/issues/6446#issuecomment-173459525
    // this is a class of application bootstrap component (like my-app)
    var classOfRootComponent = this.applicationRef.componentTypes[0];
    // this is an instance of application bootstrap component
    var appInstance = this.injector.get(classOfRootComponent);
    return appInstance.viewContainerRef;
};
```

**Comment by valorkin** [comment]
OK, I see where is issue came from I will test fix on @flibbertigibbet repo, if work I will publish fix today

**Comment by valorkin** [comment]
Guys need a sample repo with issue to reproduce, thanks in advance. Seems I have found a solution, but need to fix it first

**Comment by valorkin** [comment]
Test it *

**Comment by noxborough** [comment]
@valorkin 
I tested with RC7 and ng2-bootstrap v1.1.3

Now when i use a modal dialog inside of a component that is lazy loaded (and i have config.backdrop = "static").  It gets caught in an **infinite loop**.

In the code below, appInstance is getting set to **false** because it is not found in the injector. And the injector's parentInjector is **undefined**.

```
ComponentsHelper.prototype.getRootViewContainerRef = function (_injector) {
    // The only way for now (by @mhevery)
    // https://github.com/angular/angular/issues/6446#issuecomment-173459525
    // this is a class of application bootstrap component (like my-app)
    var classOfRootComponent = this.applicationRef.componentTypes[0];
    // this is an instance of application bootstrap component
    var appInstance;
    var injector = _injector;
    while (!appInstance) {
        appInstance = injector.get(classOfRootComponent, false);
        if (!appInstance && injector.parentInjector) {
            injector = injector.parentInjector;
        }
    }
    return appInstance.viewContainerRef;
};
```

**Comment by valorkin** [comment]
I really need a code sample, where it fails

**Comment by noxborough** [comment]
haven't ever put a plunker together. working on putting one together that demonstrates the issue

**Comment by noxborough** [comment]
@valorkin 
Ok here goes. This plunker should demonstrate the issue. As soon as you click on the "My Modal" button, it should get caught in the infinite loop. 

https://plnkr.co/edit/PLF3dN?p=info

However, if you go into my-modal.component.ts and switch from
**this.myModal.config.backdrop = "static";**
to
**this.myModal.config.backdrop = false;**
it should work.

**Comment by tungphuong** [comment]
Confirmed, It worked well. Thanks

**Comment by valorkin** [comment]
@noxborough thank you so much! working on fix

**Comment by valorkin** [comment]
@noxborough your plunker was so helpful !
publishing fix in a minutes

**Comment by valorkin** [comment]
guys, 1.1.5 is published please confirm that fix is working properly
thanks in advance
PS: don't forget to add viewContainerRef to main app component
http://valor-software.com/ng2-bootstrap/#/modals

**Comment by hassanasad** [comment]
WOW -- Thanks @valorkin after much effort from you and enough complaining from us, its finally working :)

**Comment by noxborough** [comment]
@valorkin 
no problem

I edited the plunker to use 1.1.5, and it didn't work. But only because i forgot to add the viewContainerRef hack in.  All is well now. thanks for fixing.

**Comment by valorkin** [comment]
:happy:

**Comment by tungphuong** [comment]
Updated to 1.1.5, it worked well, dont need to set this.myModal.config.backdrop = false;
Thanks @valorkin
